server:
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: budgetto

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    token-expiration: 86400 # 1 day

app:
  cors:
    allowed-origins: ${ALLOW_CORS_URLS}
    allowed-methods: ${ALLOW_CORS_METHODS}
    allowed-headers: ${ALLOW_CORS_HEADERS}
    max-age: ${CORS_MAX_AGE}
